name: universal-react-helloworld
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple Universal React.js "Hello world" Application
description: |
  Simplest possible starting point for using universal/isomorphic/shared 
  React.js + Node.js + Express.js

grade: stable
confinement: strict

apps:
  server:
    command: env NODE_PATH=$SNAP/lib/node_modules:$SNAP/lib/node_modules/universal-react/node_modules/ node $SNAP/lib/node_modules/universal-react/lib/server.js
    daemon: simple
    plugs: [network-bind]
  universal-react-helloworld:
    command: env NODE_PATH=$SNAP/lib/node_modules:$SNAP/lib/node_modules/universal-react/node_modules/ node $SNAP/lib/node_modules/universal-react/lib/server.js
    plugs: [network-bind]
parts:
  universal-react-helloworld:
    plugin: nodejs
    source: .
    node-engine: 7.7.2
    npm-run:
      - build
      - bundle
